/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.HocSinhBLL;
import DAL.HocSinhDAL;
import DTO.HocSinhDTO;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class F_HocSinh extends javax.swing.JFrame {

    /**
     * Creates new form F_HocSinh
     */
    public F_HocSinh() {
        initComponents();
        showdata();
    }

    public void showdata() {
        HocSinhDAL hs = new HocSinhDAL();
        ArrayList<HocSinhDTO> list = hs.BindTable();
        String[] columnName = {"idtablehocsinh", "tenhocsinh", "gioitinh", "ngaysinh", "quequan", "diachi", "idtablelop"};
        Object[][] rows = new Object[list.size()][8];
        for (int i = 0; i < list.size(); i++) {
            rows[i][0] = list.get(i).getIdtablehocsinh();
            rows[i][1] = list.get(i).getTenhocsinh();
            rows[i][2] = list.get(i).getGioitinh();
            rows[i][3] = list.get(i).getNgaysinh();
            rows[i][4] = list.get(i).getQuequan();
            rows[i][5] = list.get(i).getDiachi();
            rows[i][6] = list.get(i).getIdtablelop();
//            if (list.get(i).getImg() != null) {
//                ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).getImg()).getImage()
//                        .getScaledInstance(120, 90, Image.SCALE_SMOOTH));
//                rows[i][7] = image;
//            } else {
//                rows[i][7] = null;
//            }
        }
        TheModel2 model = new TheModel2(rows, columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(90);
       // jTable1.getColumnModel().getColumn(7).setPreferredWidth(120);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nam = new javax.swing.JRadioButton();
        nu = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmahs = new javax.swing.JTextField();
        txttenhs = new javax.swing.JTextField();
        txtquequan = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txtmalop = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnchonhinh = new javax.swing.JButton();
        labelhienthihinh = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Học Sinh", "Tên Học Sinh", "Giới Tính", "Ngày Sinh", "Quê Quán", "Địa Chỉ", "Mã Lớp"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Mã học sinh");

        jLabel2.setText("Tên học sinh");

        nam.setText("nam");
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });

        nu.setText("nữ");
        nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuActionPerformed(evt);
            }
        });

        jLabel3.setText("Giới tính");

        jLabel4.setText("Ngày Sinh");

        jLabel5.setText("Quê quán");

        jLabel6.setText("Địa Chỉ");

        jLabel7.setText("Mã lớp");

        txtmahs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmahsActionPerformed(evt);
            }
        });

        btnadd.setText("thêm");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setText("sửa");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("xóa");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnchonhinh.setText("chon hinh");
        btnchonhinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonhinhActionPerformed(evt);
            }
        });

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel8.setText("Tìm Kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnchonhinh)
                                .addGap(41, 41, 41)
                                .addComponent(labelhienthihinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(84, 84, 84)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtquequan, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmalop, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nam)
                                .addGap(78, 78, 78)
                                .addComponent(nu))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtmahs, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                .addComponent(txttenhs)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(169, 169, 169)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtmahs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txttenhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nu)
                            .addComponent(nam)
                            .addComponent(jLabel3))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtquequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtmalop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnchonhinh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(labelhienthihinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
        if (nam.isSelected()) {
            nu.setSelected(false);
        }
    }//GEN-LAST:event_namActionPerformed

    private void txtmahsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmahsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmahsActionPerformed

    // lấy dữ liệu từ bảng vào các text
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        txtmahs.setText(model.getValueAt(i, 0).toString());
        txttenhs.setText(model.getValueAt(i, 1).toString());
        // lấy giá trị giới tính
        try {
            if ("nam".equals(model.getValueAt(i, 2).toString()) == true) {
                nam.setSelected(true);
                nu.setSelected(false);
            }
            if ("nữ".equals(model.getValueAt(i, 2).toString()) == true) {
                nam.setSelected(false);
                nu.setSelected(true);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "khong lay duoc gia tri gioi tinh");
        }
        //ngày sinh
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(i, 3));
            jDateChooser1.setDate(date);
        } catch (ParseException e) {
            JOptionPane.showConfirmDialog(null, "khong lay duoc gia tri ngay thang");
        }
        //quê quán
        txtquequan.setText(model.getValueAt(i, 4).toString());
        txtdiachi.setText(model.getValueAt(i, 5).toString());
        txtmalop.setText(model.getValueAt(i, 6).toString());

        // lấy hình ảnh
        if (jTable1.getValueAt(i, 7) != null) {
            ImageIcon image1 = (ImageIcon) jTable1.getValueAt(i, 7);
            Image image2 = image1.getImage().getScaledInstance(labelhienthihinh.getWidth(), labelhienthihinh.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image3 = new ImageIcon(image2);
            labelhienthihinh.setIcon(image3);
            // test laays hinh khi click vao table
            photo1 = null;

        } else if (jTable1.getValueAt(i, 7) == null) {
            labelhienthihinh.setIcon(null);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuActionPerformed
        // TODO add your handling code here:
        if (nu.isSelected()) {
            nam.setSelected(false);
        }
    }//GEN-LAST:event_nuActionPerformed

    private void btnchonhinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonhinhActionPerformed
        // TODO add your handling code here:
        String AR = "";
        FileNameExtensionFilter typephoto = new FileNameExtensionFilter("Định dạng ảnh(*.jpg; *.png; *.jpeg)", "jpg", "png", "jpeg");
        JFileChooser file = new JFileChooser();
        file.addChoosableFileFilter(typephoto);
        file.setDialogTitle("Chọn ảnh");
        int window = file.showOpenDialog(null);
        if (window == JFileChooser.APPROVE_OPTION) {

            File ar = file.getSelectedFile();
            Image photo = getToolkit().getImage(String.valueOf(ar));
            AR = String.valueOf(ar);
            photo = photo.getScaledInstance(labelhienthihinh.getWidth(), labelhienthihinh.getHeight(), Image.SCALE_DEFAULT);
            labelhienthihinh.setIcon(new ImageIcon(photo));
            filename = ar.getAbsolutePath();
            try {
                File image = new File(filename);
                FileInputStream fis = new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buf = new byte[1024];
                for (int readNum; (readNum = fis.read(buf)) != -1;) {
                    bos.write(buf, 0, readNum);
                }
                photo1 = bos.toByteArray();
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnchonhinhActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String id = txtmahs.getText();
        String ten = txttenhs.getText();
        //gioi tinh
        String gioitinh = null;
        if (nam.isSelected()) {
            gioitinh = "nam";
        }
        if (nu.isSelected()) {
            gioitinh = "nữ";
        }

        //ngay sinh
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(jDateChooser1.getDate());
        //que quan
        String quequan = txtquequan.getText();
        String diachi = txtdiachi.getText();
        String malop = txtmalop.getText();
        HocSinhDTO hocSinhDTO = new HocSinhDTO(id, ten, gioitinh, date, quequan, diachi, malop, photo1);
        HocSinhBLL hocSinhBLL = new HocSinhBLL();
        if (hocSinhBLL.AddHS(hocSinhDTO) == true) {
            TableModel model = jTable1.getModel();
            showdata();
            JOptionPane.showConfirmDialog(null, "thanh cong");
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        TableModel model = jTable1.getModel();
        String search = txtsearch.getText();
        TableRowSorter<TableModel> trl = new TableRowSorter<>(model);
        jTable1.setRowSorter(trl);
        trl.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txtsearchKeyReleased

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        String id = txtmahs.getText();
        String ten = txttenhs.getText();
        //gioi tinh
        String gioitinh = null;
        if (nam.isSelected()) {
            gioitinh = "nam";
        }
        if (nu.isSelected()) {
            gioitinh = "nữ";
        }

        //ngay sinh
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(jDateChooser1.getDate());
        //que quan
        String quequan = txtquequan.getText();
        String diachi = txtdiachi.getText();
        String malop = txtmalop.getText();

        HocSinhDTO hocSinhDTO = new HocSinhDTO(id, ten, gioitinh, date, quequan, diachi, malop, photo1);
        HocSinhBLL hocSinhBLL = new HocSinhBLL();

        //update neu co hinh anh
        if (photo1 != null) {
            if (hocSinhBLL.UpdateHS(hocSinhDTO) == true) {
                TableModel model = jTable1.getModel();
                showdata();
                JOptionPane.showConfirmDialog(null, "thanh cong");
            }
        }
        if (photo1 == null) {
            if (hocSinhBLL.UpdateHS2(hocSinhDTO) == true) {
                TableModel model = jTable1.getModel();
                showdata();
                JOptionPane.showConfirmDialog(null, "thanh cong");
            }
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        String id = txtmahs.getText();
        HocSinhBLL hocSinhBLL = new HocSinhBLL();

        if (hocSinhBLL.DeleteHS(id) == true) {
            TableModel model = jTable1.getModel();
            showdata();
            JOptionPane.showConfirmDialog(null, "thanh cong");
        }

    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_HocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_HocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_HocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_HocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_HocSinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnchonhinh;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelhienthihinh;
    private javax.swing.JRadioButton nam;
    private javax.swing.JRadioButton nu;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtmahs;
    private javax.swing.JTextField txtmalop;
    private javax.swing.JTextField txtquequan;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txttenhs;
    // End of variables declaration//GEN-END:variables
    String filename = null;
    byte[] photo1 = null;
}
