/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.monHocBLL;
import DAL.monHocDAL;
import DTO.monHocDTO;
import UTILS.ConnectionUtil;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author HP
 */
public class F_MonHoc extends javax.swing.JFrame {

    /**
     * Creates new form F_MonHoc
     */
    //lấy danh sách
    public ArrayList<monHocDTO> getListMonhoc() {

        ArrayList<monHocDTO> list = new ArrayList<monHocDTO>();
        String sql = "SELECT * FROM doan.tablemonhoc";
        Statement st;
        ResultSet rs;

        try {
            ConnectionUtil conUtil = new ConnectionUtil();
            Connection con = conUtil.getConnection();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            monHocDTO monhocDTO;

            while (rs.next()) {
                monhocDTO = new monHocDTO(rs.getString("idtablemonhoc"), rs.getString("tenmonhoc"), rs.getInt("sotiet"));
                list.add(monhocDTO);
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("loi hien thi mon hoc");
        }
        return list;
    }

    public F_MonHoc() {
        initComponents();
        showdatatintable();
    }

    public void showdatatintable() {
        //ArrayList<monHocDTO> list = new ArrayList<monHocDTO>();
        //list = monhocDAL.getListMonhoc();
        ArrayList<monHocDTO> list = getListMonhoc();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getIdtablemonhoc();
            row[1] = list.get(i).getTenmonhoc();
            row[2] = list.get(i).getSotiet();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmamonhoc = new javax.swing.JTextField();
        txttenmonhoc = new javax.swing.JTextField();
        txtsotiet = new javax.swing.JTextField();
        bttthemmonhoc = new javax.swing.JButton();
        bttsuamonhoc = new javax.swing.JButton();
        bttxoamonhoc = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã môn học", "Tên môn học", "Số tiết"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Mã môn học");

        jLabel2.setText("Tên môn học");

        jLabel3.setText("Số tiết");

        txtsotiet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsotietKeyPressed(evt);
            }
        });

        bttthemmonhoc.setText("thêm");
        bttthemmonhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttthemmonhocActionPerformed(evt);
            }
        });

        bttsuamonhoc.setText("sửa");
        bttsuamonhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttsuamonhocActionPerformed(evt);
            }
        });

        bttxoamonhoc.setText("xóa");
        bttxoamonhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttxoamonhocActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel4.setText("tìm kiếm");

        mess.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmamonhoc)
                                    .addComponent(txttenmonhoc, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtsotiet, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(bttthemmonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(bttsuamonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(bttxoamonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmamonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttenmonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsotiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttthemmonhoc)
                    .addComponent(bttsuamonhoc)
                    .addComponent(bttxoamonhoc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //button thêm mới môn học
    private void bttthemmonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttthemmonhocActionPerformed
        // TODO add your handling code here:
        String id = txtmamonhoc.getText();
        String ten = txttenmonhoc.getText();
        int sotiet = Integer.parseInt(txtsotiet.getText());
        monHocDTO monhocDTO = new monHocDTO(id, ten, sotiet);
        monHocBLL monhocBLL = new monHocBLL();
        try {
            if (monhocBLL.AddMonhoc(monhocDTO) == true) {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                showdatatintable();
                JOptionPane.showConfirmDialog(null, "thanh cong");
            } else {
                JOptionPane.showConfirmDialog(null, "khong thanh cong");
            }
        } catch (ClassNotFoundException ex) {

            System.out.println("sai GUI");
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_bttthemmonhocActionPerformed

    //button sửa môn học
    private void bttsuamonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttsuamonhocActionPerformed
        // TODO add your handling code here:
        String id = txtmamonhoc.getText();
        String ten = txttenmonhoc.getText();
        int sotiet = Integer.parseInt(txtsotiet.getText());
        monHocDTO monhocDTO = new monHocDTO(id, ten, sotiet);
        monHocBLL monhocBLL = new monHocBLL();
        try {
            if (monhocBLL.UpdateMonhoc(monhocDTO) == true) {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                showdatatintable();
                JOptionPane.showConfirmDialog(null, "thanh cong");
            } else {
                JOptionPane.showConfirmDialog(null, "khong thanh cong");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bttsuamonhocActionPerformed

    //button xóa
    private void bttxoamonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttxoamonhocActionPerformed
        // TODO add your handling code here:
        String id = txtmamonhoc.getText();
        monHocBLL monhocBLL = new monHocBLL();
        monHocDTO monhocDTO = new monHocDTO(id, null, 0);
        try {
            if (monhocBLL.DeleteMonhoc(monhocDTO) == true) {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                showdatatintable();
                JOptionPane.showConfirmDialog(null, "thanh cong");
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "không thanh cong");
        }
    }//GEN-LAST:event_bttxoamonhocActionPerformed

    //lấy dữ liệu từ bảng vào JTextFiled
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();

        // Display Slected Row In JTexteFields
        txtmamonhoc.setText(model.getValueAt(i, 0).toString());
        txttenmonhoc.setText(model.getValueAt(i, 1).toString());
        int getSotiet = Integer.parseInt(model.getValueAt(i, 2).toString());
        String s = String.valueOf(getSotiet);
        txtsotiet.setText(s);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String search1 = txtSearch.getText();
        TableRowSorter<DefaultTableModel> tr1 = new TableRowSorter<DefaultTableModel>(model);
        jTable1.setRowSorter(tr1);
        tr1.setRowFilter(RowFilter.regexFilter(search1));
        // tìm kiếm có phân biệt
//        String search2 = txtSearch.getText();
//        TableRowSorter<DefaultTableModel> tr2 = new TableRowSorter<DefaultTableModel>(model);
//        jTable1.setRowSorter(tr2);
//        tr2.setRowFilter(RowFilter.regexFilter(search2));
    }//GEN-LAST:event_txtSearchKeyReleased

    //thông báo khi nhập sai
    private void txtsotietKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsotietKeyPressed
        // TODO add your handling code here:
        try {
            int i=Integer.parseInt(txtsotiet.getText());
            mess.setText("");
        } catch (NumberFormatException e) {
            mess.setText("vui lòng nhập vào số");
        }
    }//GEN-LAST:event_txtsotietKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_MonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_MonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_MonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_MonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_MonHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttsuamonhoc;
    private javax.swing.JButton bttthemmonhoc;
    private javax.swing.JButton bttxoamonhoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mess;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtmamonhoc;
    private javax.swing.JTextField txtsotiet;
    private javax.swing.JTextField txttenmonhoc;
    // End of variables declaration//GEN-END:variables
}
