/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author hunte
 */
public class Main_Form extends javax.swing.JFrame {

    /**
     * Creates new form Main_Form
     */
    public Main_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navBar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        navBar_bar = new javax.swing.JPanel();
        nav_item_qlhs = new javax.swing.JButton();
        nav_item_qld = new javax.swing.JButton();
        nav_item_tk = new javax.swing.JButton();
        nav_item_setting = new javax.swing.JButton();
        main_content = new javax.swing.JPanel();
        quanLyHS = new javax.swing.JPanel();
        navBar_bar1 = new javax.swing.JPanel();
        sub_qlhs_hs = new javax.swing.JButton();
        sub_qlhs_gv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        qlhs_content = new javax.swing.JPanel();
        F_HocSinh = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtmahs = new javax.swing.JTextField();
        nam = new javax.swing.JRadioButton();
        nu = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txttenhs = new javax.swing.JTextField();
        txtquequan = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txtmalop = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        F_GiaoVien = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtidgiaovien = new javax.swing.JTextField();
        nam1 = new javax.swing.JRadioButton();
        nu1 = new javax.swing.JRadioButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        txttenhs1 = new javax.swing.JTextField();
        btnadd1 = new javax.swing.JButton();
        btnupdate1 = new javax.swing.JButton();
        btndelete1 = new javax.swing.JButton();
        quanLyDiem = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        thongKe = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        navBar.setBackground(new java.awt.Color(204, 255, 255));
        navBar.setPreferredSize(new java.awt.Dimension(1600, 45));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N

        navBar_bar.setBackground(new java.awt.Color(204, 204, 204));
        navBar_bar.setPreferredSize(new java.awt.Dimension(1346, 45));

        nav_item_qlhs.setBackground(new java.awt.Color(204, 204, 204));
        nav_item_qlhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Quản lý hồ sơ.png"))); // NOI18N
        nav_item_qlhs.setToolTipText("");
        nav_item_qlhs.setBorderPainted(false);
        nav_item_qlhs.setContentAreaFilled(false);
        nav_item_qlhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_item_qlhs.setFocusPainted(false);
        nav_item_qlhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nav_item_qlhsActionPerformed(evt);
            }
        });

        nav_item_qld.setBackground(new java.awt.Color(204, 204, 204));
        nav_item_qld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Quản lý điểm.png"))); // NOI18N
        nav_item_qld.setToolTipText("");
        nav_item_qld.setBorderPainted(false);
        nav_item_qld.setContentAreaFilled(false);
        nav_item_qld.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_item_qld.setFocusPainted(false);
        nav_item_qld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nav_item_qldActionPerformed(evt);
            }
        });

        nav_item_tk.setBackground(new java.awt.Color(204, 204, 204));
        nav_item_tk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Thống kê.png"))); // NOI18N
        nav_item_tk.setToolTipText("");
        nav_item_tk.setBorderPainted(false);
        nav_item_tk.setContentAreaFilled(false);
        nav_item_tk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_item_tk.setFocusPainted(false);
        nav_item_tk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nav_item_tkActionPerformed(evt);
            }
        });

        nav_item_setting.setBackground(new java.awt.Color(204, 204, 204));
        nav_item_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setting.png"))); // NOI18N
        nav_item_setting.setToolTipText("");
        nav_item_setting.setBorderPainted(false);
        nav_item_setting.setContentAreaFilled(false);
        nav_item_setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_item_setting.setFocusPainted(false);
        nav_item_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_item_settingMouseClicked(evt);
            }
        });
        nav_item_setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nav_item_settingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navBar_barLayout = new javax.swing.GroupLayout(navBar_bar);
        navBar_bar.setLayout(navBar_barLayout);
        navBar_barLayout.setHorizontalGroup(
            navBar_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBar_barLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nav_item_qlhs)
                .addGap(15, 15, 15)
                .addComponent(nav_item_qld)
                .addGap(15, 15, 15)
                .addComponent(nav_item_tk)
                .addGap(15, 15, 15)
                .addComponent(nav_item_setting)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navBar_barLayout.setVerticalGroup(
            navBar_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBar_barLayout.createSequentialGroup()
                .addGroup(navBar_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nav_item_qlhs)
                    .addComponent(nav_item_qld)
                    .addComponent(nav_item_tk))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(navBar_barLayout.createSequentialGroup()
                .addComponent(nav_item_setting)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navBarLayout = new javax.swing.GroupLayout(navBar);
        navBar.setLayout(navBarLayout);
        navBarLayout.setHorizontalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navBar_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navBarLayout.setVerticalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navBar_bar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        main_content.setBackground(new java.awt.Color(204, 255, 255));
        main_content.setPreferredSize(new java.awt.Dimension(1600, 900));
        main_content.setLayout(new java.awt.CardLayout());

        quanLyHS.setBackground(new java.awt.Color(255, 255, 255));
        quanLyHS.setPreferredSize(new java.awt.Dimension(1600, 900));

        navBar_bar1.setBackground(new java.awt.Color(76, 187, 214));
        navBar_bar1.setPreferredSize(new java.awt.Dimension(1600, 45));

        sub_qlhs_hs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HocSinh.png"))); // NOI18N
        sub_qlhs_hs.setBorderPainted(false);
        sub_qlhs_hs.setContentAreaFilled(false);
        sub_qlhs_hs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sub_qlhs_hs.setFocusPainted(false);
        sub_qlhs_hs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_qlhs_hsActionPerformed(evt);
            }
        });

        sub_qlhs_gv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GiaoVien.png"))); // NOI18N
        sub_qlhs_gv.setBorderPainted(false);
        sub_qlhs_gv.setContentAreaFilled(false);
        sub_qlhs_gv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sub_qlhs_gv.setFocusPainted(false);
        sub_qlhs_gv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_qlhs_gvActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qlhs.png"))); // NOI18N

        javax.swing.GroupLayout navBar_bar1Layout = new javax.swing.GroupLayout(navBar_bar1);
        navBar_bar1.setLayout(navBar_bar1Layout);
        navBar_bar1Layout.setHorizontalGroup(
            navBar_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBar_bar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sub_qlhs_hs)
                .addGap(26, 26, 26)
                .addComponent(sub_qlhs_gv)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        navBar_bar1Layout.setVerticalGroup(
            navBar_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBar_bar1Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(navBar_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sub_qlhs_hs, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sub_qlhs_gv, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        qlhs_content.setBackground(new java.awt.Color(255, 255, 255));
        qlhs_content.setPreferredSize(new java.awt.Dimension(1600, 1600));
        qlhs_content.setLayout(new java.awt.CardLayout());

        F_HocSinh.setBackground(new java.awt.Color(255, 255, 255));
        F_HocSinh.setPreferredSize(new java.awt.Dimension(1600, 804));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Thong tin hs.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("Mã học sinh");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Tên học sinh");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Giới tính");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setText("Ngày sinh");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setText("Quê quán");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setText("Địa chỉ");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("Mã lớp");

        txtmahs.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txtmahs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmahs.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtmahs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmahsActionPerformed(evt);
            }
        });

        nam.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nam.setText("nam");
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });

        nu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nu.setText("Nữ");
        nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuActionPerformed(evt);
            }
        });

        txttenhs.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txttenhs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttenhs.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtquequan.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txtquequan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtquequan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtdiachi.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txtdiachi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdiachi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtmalop.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txtmalop.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmalop.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnadd.setBorder(null);
        btnadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnupdate.setBorder(null);
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.png"))); // NOI18N
        btndelete.setBorder(null);
        btndelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(nam)
                                                .addGap(44, 44, 44)
                                                .addComponent(nu))
                                            .addComponent(txtmahs, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txttenhs)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtquequan)
                                            .addComponent(txtdiachi)
                                            .addComponent(txtmalop)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnadd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnupdate)
                                .addGap(83, 83, 83)
                                .addComponent(btndelete)))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmahs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttenhs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtquequan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmalop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd)
                    .addComponent(btndelete)
                    .addComponent(btnupdate))
                .addGap(65, 65, 65))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout F_HocSinhLayout = new javax.swing.GroupLayout(F_HocSinh);
        F_HocSinh.setLayout(F_HocSinhLayout);
        F_HocSinhLayout.setHorizontalGroup(
            F_HocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(F_HocSinhLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        F_HocSinhLayout.setVerticalGroup(
            F_HocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        qlhs_content.add(F_HocSinh, "card2");

        F_GiaoVien.setBackground(new java.awt.Color(255, 255, 255));
        F_GiaoVien.setPreferredSize(new java.awt.Dimension(1600, 804));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(583, 804));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thong tin gv.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setText("Mã giáo viên");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setText("Tên giáo viên");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setText("Giới tính");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setText("Ngày sinh");

        txtidgiaovien.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txtidgiaovien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidgiaovien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtidgiaovien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidgiaovienActionPerformed(evt);
            }
        });

        nam1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nam1.setText("nam");
        nam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nam1ActionPerformed(evt);
            }
        });

        nu1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nu1.setText("Nữ");
        nu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nu1ActionPerformed(evt);
            }
        });

        txttenhs1.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txttenhs1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttenhs1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnadd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnadd1.setBorder(null);
        btnadd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnupdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnupdate1.setBorder(null);
        btnupdate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btndelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.png"))); // NOI18N
        btndelete1.setBorder(null);
        btndelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnadd1)
                                .addGap(85, 85, 85)
                                .addComponent(btnupdate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btndelete1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel20))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(nam1)
                                        .addGap(44, 44, 44)
                                        .addComponent(nu1)
                                        .addGap(0, 245, Short.MAX_VALUE))
                                    .addComponent(txttenhs1)
                                    .addComponent(txtidgiaovien)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(45, 45, 45)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidgiaovien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttenhs1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nam1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nu1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnupdate1)
                    .addComponent(btnadd1)
                    .addComponent(btndelete1))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout F_GiaoVienLayout = new javax.swing.GroupLayout(F_GiaoVien);
        F_GiaoVien.setLayout(F_GiaoVienLayout);
        F_GiaoVienLayout.setHorizontalGroup(
            F_GiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(F_GiaoVienLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        F_GiaoVienLayout.setVerticalGroup(
            F_GiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        qlhs_content.add(F_GiaoVien, "card3");

        javax.swing.GroupLayout quanLyHSLayout = new javax.swing.GroupLayout(quanLyHS);
        quanLyHS.setLayout(quanLyHSLayout);
        quanLyHSLayout.setHorizontalGroup(
            quanLyHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(qlhs_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navBar_bar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1609, Short.MAX_VALUE)
        );
        quanLyHSLayout.setVerticalGroup(
            quanLyHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quanLyHSLayout.createSequentialGroup()
                .addComponent(navBar_bar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qlhs_content, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE))
        );

        main_content.add(quanLyHS, "card2");

        quanLyDiem.setBackground(new java.awt.Color(204, 204, 255));
        quanLyDiem.setPreferredSize(new java.awt.Dimension(1600, 900));

        jLabel2.setText("Quản lý điểm");

        javax.swing.GroupLayout quanLyDiemLayout = new javax.swing.GroupLayout(quanLyDiem);
        quanLyDiem.setLayout(quanLyDiemLayout);
        quanLyDiemLayout.setHorizontalGroup(
            quanLyDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quanLyDiemLayout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jLabel2)
                .addContainerGap(1186, Short.MAX_VALUE))
        );
        quanLyDiemLayout.setVerticalGroup(
            quanLyDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quanLyDiemLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel2)
                .addContainerGap(501, Short.MAX_VALUE))
        );

        main_content.add(quanLyDiem, "card3");

        thongKe.setBackground(new java.awt.Color(255, 204, 255));
        thongKe.setPreferredSize(new java.awt.Dimension(1600, 900));

        jLabel3.setText("Thống kê");

        javax.swing.GroupLayout thongKeLayout = new javax.swing.GroupLayout(thongKe);
        thongKe.setLayout(thongKeLayout);
        thongKeLayout.setHorizontalGroup(
            thongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeLayout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jLabel3)
                .addContainerGap(1204, Short.MAX_VALUE))
        );
        thongKeLayout.setVerticalGroup(
            thongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel3)
                .addContainerGap(501, Short.MAX_VALUE))
        );

        main_content.add(thongKe, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main_content, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //nav-item quản lý học sinh
    private void nav_item_qlhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_item_qlhsActionPerformed
        // TODO add your handling code here:
        //remove tất cả panel
        
        main_content.removeAll();
        main_content.repaint();
        main_content.revalidate();
        
        //add panel quản lý học sinh
        main_content.add(quanLyHS);
        main_content.repaint();
        main_content.revalidate();
             
    }//GEN-LAST:event_nav_item_qlhsActionPerformed

    private void nav_item_qldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_item_qldActionPerformed
        // TODO add your handling code here:
        //remove tất cả panel
        
        main_content.removeAll();
        main_content.repaint();
        main_content.revalidate();
        
        //add panel quản lý điểm
        main_content.add(quanLyDiem);
        main_content.repaint();
        main_content.revalidate();
    }//GEN-LAST:event_nav_item_qldActionPerformed

    private void nav_item_tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_item_tkActionPerformed
        // TODO add your handling code here:
        //remove tất cả panel
        
        main_content.removeAll();
        main_content.repaint();
        main_content.revalidate();
        
        //add panel thống kê
        main_content.add(thongKe);
        main_content.repaint();
        main_content.revalidate();
    }//GEN-LAST:event_nav_item_tkActionPerformed

    //show dropdown menu
    private void nav_item_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_item_settingMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nav_item_settingMouseClicked

    private void nav_item_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_item_settingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_item_settingActionPerformed

    private void sub_qlhs_hsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_qlhs_hsActionPerformed
        // TODO add your handling code here:
        qlhs_content.removeAll();
        qlhs_content.repaint();
        qlhs_content.revalidate();
        
        //add panel Quan ly ho so: `Hoc Sinh`
        qlhs_content.add(F_HocSinh);
        qlhs_content.repaint();
        qlhs_content.revalidate();
    }//GEN-LAST:event_sub_qlhs_hsActionPerformed

    private void sub_qlhs_gvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_qlhs_gvActionPerformed
        // TODO add your handling code here:
        qlhs_content.removeAll();
        qlhs_content.repaint();
        qlhs_content.revalidate();
        
        //add panel Quan ly ho so: `Giao Vien`
        qlhs_content.add(F_GiaoVien);
        qlhs_content.repaint();
        qlhs_content.revalidate();
    }//GEN-LAST:event_sub_qlhs_gvActionPerformed

    private void txtmahsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmahsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmahsActionPerformed

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
        if (nam.isSelected()) {
            nu.setSelected(false);
        }
    }//GEN-LAST:event_namActionPerformed

    private void nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuActionPerformed
        // TODO add your handling code here:
        if (nu.isSelected()) {
            nam.setSelected(false);
        }
    }//GEN-LAST:event_nuActionPerformed

    private void txtidgiaovienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidgiaovienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidgiaovienActionPerformed

    private void nam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nam1ActionPerformed

    private void nu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nu1ActionPerformed

    private void btndelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndelete1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel F_GiaoVien;
    private javax.swing.JPanel F_HocSinh;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndelete1;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnupdate1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel main_content;
    private javax.swing.JRadioButton nam;
    private javax.swing.JRadioButton nam1;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel navBar_bar;
    private javax.swing.JPanel navBar_bar1;
    private javax.swing.JButton nav_item_qld;
    private javax.swing.JButton nav_item_qlhs;
    private javax.swing.JButton nav_item_setting;
    private javax.swing.JButton nav_item_tk;
    private javax.swing.JRadioButton nu;
    private javax.swing.JRadioButton nu1;
    private javax.swing.JPanel qlhs_content;
    private javax.swing.JPanel quanLyDiem;
    private javax.swing.JPanel quanLyHS;
    private javax.swing.JButton sub_qlhs_gv;
    private javax.swing.JButton sub_qlhs_hs;
    private javax.swing.JPanel thongKe;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtidgiaovien;
    private javax.swing.JTextField txtmahs;
    private javax.swing.JTextField txtmalop;
    private javax.swing.JTextField txtquequan;
    private javax.swing.JTextField txttenhs;
    private javax.swing.JTextField txttenhs1;
    // End of variables declaration//GEN-END:variables
}
